#include "FhdbConfig.h"

#include <algorithm>
#include <cctype>
#include <map>
#include <set>
#include <stdexcept>

namespace Ps2
{

FhdbConfig::FhdbConfig() = default;

std::string FhdbConfig::trim(const std::string &value)
{
    const auto first = std::find_if_not(value.begin(), value.end(), [](unsigned char character) {
        return std::isspace(character) != 0;
    });
    const auto last = std::find_if_not(value.rbegin(), value.rend(), [](unsigned char character) {
        return std::isspace(character) != 0;
    }).base();
    return first < last ? std::string(first, last) : std::string();
}

FhdbConfig::Line FhdbConfig::parseLine(const std::string &text)
{
    Line line;
    line.raw = text;
    const std::string cleaned = trim(text);
    if (cleaned.empty() || cleaned.front() == '#')
        return line;

    const std::size_t equals = text.find('=');
    if (equals == std::string::npos)
        return line;
    line.key = trim(text.substr(0, equals));
    if (line.key.empty())
        return line;
    line.value = trim(text.substr(equals + 1));
    line.assignment = true;
    return line;
}

FhdbConfig::Line FhdbConfig::assignment(const std::string &key, const std::string &value)
{
    Line line;
    line.assignment = true;
    line.key = key;
    line.value = value;
    line.raw = key + " = " + value;
    return line;
}

FhdbConfig FhdbConfig::Parse(const std::string &text)
{
    FhdbConfig result;
    result.newline = text.find("\r\n") != std::string::npos ? "\r\n" : "\n";
    result.finalNewline = !text.empty() && text.back() == '\n';

    std::size_t position = 0;
    while (position < text.size())
    {
        const std::size_t end = text.find('\n', position);
        const std::size_t length = end == std::string::npos ? text.size() - position : end - position;
        std::string line = text.substr(position, length);
        if (!line.empty() && line.back() == '\r')
            line.pop_back();
        result.lines.push_back(parseLine(line));
        if (end == std::string::npos)
            break;
        position = end + 1;
    }
    return result;
}

FhdbConfig FhdbConfig::CreateDefault()
{
    return Parse(
            "# Free HDBoot configuration generated by PS2 HDD Manager\n"
            "CNF_version = 1\n"
            "Debug_Screen = 0\n"
            "FastBoot = 1\n"
            "pad_delay = 0\n"
            "LK_Auto_E1 = OSDSYS\n"
            "LK_Auto_E3 = OSDSYS\n"
            "hacked_OSDSYS = 1\n"
            "OSDSYS_video_mode = AUTO\n"
            "OSDSYS_Skip_Logo = 1\n"
            "OSDSYS_Skip_Disc = 0\n"
            "OSDSYS_Inner_Browser = 2\n"
            "OSDSYS_scroll_menu = 1\n"
            "OSDSYS_num_displayed_items = 7\n"
            "OSDSYS_Skip_MC = 1\n"
            "OSDSYS_Skip_HDD = 1\n"
            "\n"
            "name_OSDSYS_ITEM_1 = Open PS2 Loader\n"
            "path1_OSDSYS_ITEM_1 = hdd0:PP.FHDB.APPS:pfs:/OPL/OPNPS2LD.ELF\n"
            "name_OSDSYS_ITEM_2 = wLaunchELF\n"
            "path1_OSDSYS_ITEM_2 = hdd0:__sysconf:pfs:/FMCB/BOOT.ELF\n"
            "name_OSDSYS_ITEM_98 = Free HDBoot Configurator\n"
            "path1_OSDSYS_ITEM_98 = hdd0:__sysconf:pfs:/FMCB/FMCB_CFG.ELF\n"
            "name_OSDSYS_ITEM_99 = Restart System\n"
            "path1_OSDSYS_ITEM_99 = OSDSYS\n"
            "name_OSDSYS_ITEM_100 = Shutdown System\n"
            "path1_OSDSYS_ITEM_100 = POWEROFF\n");
}

std::string FhdbConfig::Serialize() const
{
    std::string result;
    for (std::size_t index = 0; index < lines.size(); index++)
    {
        const Line &line = lines[index];
        result += line.assignment ? line.key + " = " + line.value : line.raw;
        if (index + 1 < lines.size() || finalNewline)
            result += newline;
    }
    return result;
}

std::string FhdbConfig::Value(const std::string &key) const
{
    std::string result;
    for (const Line &line : lines)
        if (line.assignment && line.key == key)
            result = line.value;
    return result;
}

void FhdbConfig::SetValue(const std::string &key, const std::string &value)
{
    bool found = false;
    for (auto iterator = lines.begin(); iterator != lines.end();)
    {
        if (!iterator->assignment || iterator->key != key)
        {
            ++iterator;
            continue;
        }
        if (!found)
        {
            iterator->value = value;
            iterator->raw = key + " = " + value;
            found = true;
            ++iterator;
        }
        else
            iterator = lines.erase(iterator);
    }
    if (!found)
        lines.push_back(assignment(key, value));
}

void FhdbConfig::RemoveValue(const std::string &key)
{
    lines.erase(std::remove_if(lines.begin(), lines.end(), [&key](const Line &line) {
        return line.assignment && line.key == key;
    }), lines.end());
}

bool FhdbConfig::parseMenuKey(const std::string &key, int &index, int &field)
{
    static const std::string namePrefix = "name_OSDSYS_ITEM_";
    static const std::string pathPrefixes[] = {
        "path1_OSDSYS_ITEM_", "path2_OSDSYS_ITEM_", "path3_OSDSYS_ITEM_"
    };

    std::string number;
    if (key.compare(0, namePrefix.size(), namePrefix) == 0)
    {
        field = 0;
        number = key.substr(namePrefix.size());
    }
    else
    {
        bool matched = false;
        for (int path = 0; path < 3; path++)
        {
            const std::string &prefix = pathPrefixes[path];
            if (key.compare(0, prefix.size(), prefix) == 0)
            {
                field = path + 1;
                number = key.substr(prefix.size());
                matched = true;
                break;
            }
        }
        if (!matched)
            return false;
    }

    if (number.empty() || !std::all_of(number.begin(), number.end(), [](unsigned char character) {
            return std::isdigit(character) != 0;
        }))
        return false;
    try
    {
        index = std::stoi(number);
    }
    catch (...)
    {
        return false;
    }
    return index > 0;
}

std::vector<FhdbMenuItem> FhdbConfig::MenuItems() const
{
    std::map<int, FhdbMenuItem> items;
    for (const Line &line : lines)
    {
        if (!line.assignment)
            continue;
        int index = 0;
        int field = 0;
        if (!parseMenuKey(line.key, index, field))
            continue;
        FhdbMenuItem &item = items[index];
        item.index = index;
        switch (field)
        {
            case 0: item.name = line.value; break;
            case 1: item.path1 = line.value; break;
            case 2: item.path2 = line.value; break;
            case 3: item.path3 = line.value; break;
        }
    }

    std::vector<FhdbMenuItem> result;
    result.reserve(items.size());
    for (const auto &entry : items)
        result.push_back(entry.second);
    return result;
}

void FhdbConfig::SetMenuItems(const std::vector<FhdbMenuItem> &items)
{
    std::set<int> usedIndices;
    for (const FhdbMenuItem &item : items)
    {
        if (item.index <= 0 || item.index > 999)
            throw std::invalid_argument("FHDB menu item numbers must be between 1 and 999.");
        if (!usedIndices.insert(item.index).second)
            throw std::invalid_argument("FHDB menu item numbers must be unique.");
    }

    lines.erase(std::remove_if(lines.begin(), lines.end(), [](const Line &line) {
        int index = 0;
        int field = 0;
        return (line.assignment && parseMenuKey(line.key, index, field)) ||
                (!line.assignment && trim(line.raw) == "# FHDB menu entries");
    }), lines.end());

    if (!lines.empty() && !(lines.back().raw.empty() && !lines.back().assignment))
        lines.push_back(parseLine(std::string()));
    lines.push_back(parseLine("# FHDB menu entries"));

    for (const FhdbMenuItem &item : items)
    {
        const std::string number = std::to_string(item.index);
        if (!item.name.empty())
            lines.push_back(assignment("name_OSDSYS_ITEM_" + number, item.name));
        if (!item.path1.empty())
            lines.push_back(assignment("path1_OSDSYS_ITEM_" + number, item.path1));
        if (!item.path2.empty())
            lines.push_back(assignment("path2_OSDSYS_ITEM_" + number, item.path2));
        if (!item.path3.empty())
            lines.push_back(assignment("path3_OSDSYS_ITEM_" + number, item.path3));
    }
}

} // namespace Ps2
